const lmiList = [
  {
    "uniqueId": "ADE",
    "name": "Adelaide Bank",
    "serviceType": "residential loans",
    "lmiName": "Use Genworth LMI calc to verify and for self employ refi c\/out rental + FHOG",
    "incomeVerification": "Full Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 80,
    "lvrHigh": 81,
    "rate": 0.54,
    "lvrFixed": false,
    "valueFixed": true,
  },
  {
    "uniqueId": "ADE",
    "name": "Adelaide Bank",
    "serviceType": "residential loans",
    "lmiName": "Use Genworth LMI calc to verify and for self employ refi c\/out rental + FHOG",
    "incomeVerification": "Full Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 85,
    "lvrHigh": 86,
    "rate": 1,
    "lvrFixed": false,
    "valueFixed": true,
  },
  {
    "uniqueId": "ADE",
    "name": "Adelaide Bank",
    "serviceType": "residential loans",
    "lmiName": "Use Genworth LMI calc to verify and for self employ refi c\/out rental + FHOG",
    "incomeVerification": "Full Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 86,
    "lvrHigh": 87,
    "rate": 1.18,
    "lvrFixed": false,
    "valueFixed": true,
  },
  {
    "uniqueId": "BOM",
    "name": "Bank of Melbourne",
    "serviceType": "residential loans",
    "lmiName": "Standard Cover - Owner Occupied & Investment",
    "incomeVerification": "Full Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 85,
    "lvrHigh": 86,
    "rate": 0.83,
    "lvrFixed": false,
    "valueFixed": false,
  },
  {
    "uniqueId": "BOM",
    "name": "Bank of Melbourne",
    "serviceType": "residential loans",
    "lmiName": "Standard Cover - Owner Occupied & Investment",
    "incomeVerification": "Full Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 86,
    "lvrHigh": 87,
    "rate": 0.88,
    "lvrFixed": false,
    "valueFixed": false,
  },
  {
    "uniqueId": "BOM",
    "name": "Bank of Melbourne",
    "serviceType": "residential loans",
    "lmiName": "Loc Doc Home Loans",
    "incomeVerification": "Low Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 70,
    "lvrHigh": 72,
    "rate": 0.8,
    "lvrFixed": false,
    "valueFixed": false,
  },
  {
    "uniqueId": "BOM",
    "name": "Bank of Melbourne",
    "serviceType": "residential loans",
    "lmiName": "Loc Doc Home Loans",
    "incomeVerification": "Low Doc",
    "valueLow": 0,
    "valueHigh": 300000,
    "lvrLow": 72,
    "lvrHigh": 74,
    "rate": 0.8,
    "lvrFixed": false,
    "valueFixed": false,
  },
];

export default lmiList;
